.equ    addr_IMP, 0                     @ Implicit
.equ    addr_ACC, 1                     @ Accumulator
.equ    addr_IMM, 2                     @ Immediate

.equ    addr_ZPG, 3                     @ Zero Page
.equ    addr_ZPX, 4                     @ Zero Page, X
.equ    addr_ZPY, 5                     @ Zero Page, Y

.equ    addr_REL, 6                     @ Relative

.equ    addr_ABS, 7                     @ Absolute
.equ    addr_ABX, 8                     @ Absolute, X
.equ    addr_ABY, 9                     @ Absolute, Y

.equ    addr_IND, 10                    @ (Indirect)
.equ    addr_INX, 11                    @ (Indirect, X)
.equ    addr_INY, 12                    @ (Indirect), Y
